title: Testing How Integration with Notion
description: This is me trying to juse notion as a CMS
theme: just-the-docs

url: https://just-the-docs.github.io

search_enabled: true

search:
    heading_level: 2

color_theme: dark